apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: influencer
  namespace: nfl-schedules
spec:
  hosts:
  - "influencer.adlt.dev"
  gateways:
  - nfl-schedules-gateway-default
  http:
  - match:
    - uri:
        prefix: "/"
    route:
      - destination:
          host: influencer
          port:
            number: 8080